import { toSlug } from '@elisymlabs/husk-core';

export type Lang = 'bash' | 'python' | 'ts';

export interface ScaffoldFile {
  /** Path relative to the skill folder. */
  path: string;
  content: string;
  /** Mark the file executable (kernel scripts). */
  executable?: boolean;
}

export interface Scaffold {
  slug: string;
  files: ScaffoldFile[];
}

/**
 * Render a string as a YAML double-quoted scalar. Without this, a `name`
 * containing a newline (or `:`/`#`/quote) would inject arbitrary frontmatter
 * keys - e.g. an attacker-chosen `run:` - into the scaffolded SKILL.md.
 */
function yamlString(value: string): string {
  const escaped = value
    .replace(/\\/g, '\\\\')
    .replace(/"/g, '\\"')
    .replace(/\r/g, '\\r')
    .replace(/\n/g, '\\n')
    .replace(/\t/g, '\\t');
  return `"${escaped}"`;
}

const DOC = (name: string): string =>
  [
    '',
    `# ${name}`,
    '',
    'This is the human- and agent-facing documentation for the skill (it is also',
    'a valid Agent Skill body). The kernel reads the request from **stdin** and',
    'writes its result to **stdout**.',
    '',
  ].join('\n');

function bashSkill(name: string, slug: string): Scaffold {
  return {
    slug,
    files: [
      {
        path: 'SKILL.md',
        content:
          [
            '---',
            `name: ${yamlString(name)}`,
            'description: Echo back the text you send, in bash.',
            'run: ./run.sh',
            'input: text',
            'output: text',
            'timeout_ms: 30000',
            '---',
          ].join('\n') + DOC(name),
      },
      {
        path: 'run.sh',
        executable: true,
        content: [
          '#!/usr/bin/env bash',
          'set -euo pipefail',
          'input="$(cat)"',
          'echo "you said: ${input}"',
          '',
        ].join('\n'),
      },
    ],
  };
}

function pythonSkill(name: string, slug: string): Scaffold {
  return {
    slug,
    files: [
      {
        path: 'SKILL.md',
        content:
          [
            '---',
            `name: ${yamlString(name)}`,
            'description: Echo back the text you send, in Python.',
            'run: python3 run.py',
            'input: text',
            'output: text',
            'timeout_ms: 30000',
            '---',
          ].join('\n') + DOC(name),
      },
      {
        path: 'run.py',
        content: [
          '#!/usr/bin/env python3',
          'import sys',
          '',
          'data = sys.stdin.read()',
          'print(f"you said: {data}")',
          '',
        ].join('\n'),
      },
    ],
  };
}

function tsSkill(name: string, slug: string): Scaffold {
  return {
    slug,
    files: [
      {
        path: 'SKILL.md',
        content:
          [
            '---',
            `name: ${yamlString(name)}`,
            'description: Echo back the text you send, in TypeScript on Bun.',
            'run: ./run.ts',
            'input: text',
            'output: text',
            'timeout_ms: 30000',
            '---',
          ].join('\n') + DOC(name),
      },
      {
        path: 'run.ts',
        executable: true,
        content: [
          '#!/usr/bin/env bun',
          'const input = await Bun.stdin.text();',
          'process.stdout.write(`you said: ${input}`);',
          '',
        ].join('\n'),
      },
    ],
  };
}

/** Build the files for a new skill folder in the requested language. */
export function scaffoldSkill(name: string, lang: Lang): Scaffold {
  const slug = toSlug(name);
  switch (lang) {
    case 'python':
      return pythonSkill(name, slug);
    case 'ts':
      return tsSkill(name, slug);
    case 'bash':
    default:
      return bashSkill(name, slug);
  }
}

/** The Dockerfile emitted by `husk build --docker`. */
export function dockerfile(skillsDir: string, port: number): string {
  return [
    '# Generated by `husk build --docker`',
    'FROM oven/bun:1',
    'WORKDIR /app',
    '',
    '# Install the HUSK CLI globally.',
    'RUN bun add -g @elisymlabs/husk',
    '',
    '# If your kernels need other runtimes (python3, ffmpeg, ...), install them here:',
    '# RUN apt-get update && apt-get install -y python3 && rm -rf /var/lib/apt/lists/*',
    '',
    `COPY ${skillsDir} ./${skillsDir}`,
    '',
    `ENV HUSK_PORT=${port}`,
    `EXPOSE ${port}`,
    `CMD ["husk", "serve", "${skillsDir}", "--host", "0.0.0.0", "--port", "${port}"]`,
    '',
  ].join('\n');
}

export const DOCKERIGNORE = ['node_modules', 'dist', '.git', '.DS_Store', '*.log', ''].join('\n');
